steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/footwear-heaven-backend:$COMMIT_SHA'
      - '--build-arg'
      - 'NODE_ENV=production'
      - '-f'
      - 'Dockerfile'
      - '.'
    dir: 'backend'
    id: 'build-backend'
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/footwear-heaven-backend:$COMMIT_SHA']
    waitFor: ['build-backend']

images:
  - 'gcr.io/$PROJECT_ID/footwear-heaven-backend:$COMMIT_SHA'